# Task 2: Linear Algebra Equivalents (MATLAB to Python)

This notebook demonstrates all operations from the NumPy for MATLAB Users Linear Algebra Equivalents table.

In [2]:
# Import required libraries
import numpy as np
import scipy.linalg
import scipy.signal
from scipy.signal import decimate
from scipy.sparse.linalg import eigs, eigsh, cg

## Sample Matrices and Vectors

In [3]:
# Define sample matrices and vectors for demonstration
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])

a = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
b = np.array([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix
v = np.array([1, 2, 3])  # vector
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("A (3x3) =")
print(A)
print("\nB (3x3) =")
print(B)
print("\na (2x3) =")
print(a)
print("\nv =", v)

A (3x3) =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B (3x3) =
[[9 8 7]
 [6 5 4]
 [3 2 1]]

a (2x3) =
[[1 2 3]
 [4 5 6]]

v = [1 2 3]


## Section 1: Array Dimensions and Properties

In [4]:
# ndims(a) → np.ndim(a)
print("Number of dimensions of array a:", np.ndim(a))

Number of dimensions of array a: 2


In [5]:
# numel(a) → np.size(a)
print("Number of elements in array a:", np.size(a))

Number of elements in array a: 6


In [6]:
# size(a) → np.shape(a)
print("Shape of array a:", np.shape(a))

Shape of array a: (2, 3)


In [7]:
# size(a,n) → a.shape[n-1]
print("Size of 2nd dimension (MATLAB) / 1st dimension (Python):", a.shape[1])

Size of 2nd dimension (MATLAB) / 1st dimension (Python): 3


## Section 2: Array Creation

In [8]:
# Create 2D array
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("2D array:")
print(arr)

2D array:
[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
# zeros(3,4) → np.zeros((3, 4))
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# ones(3,4) → np.ones((3, 4))
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# eye(3) → np.eye(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# diag(a) → np.diag(a) - Extract diagonal from matrix
print("Diagonal of A:")
print(np.diag(A))

# diag(v,0) → np.diag(v, 0) - Create diagonal matrix from vector
print("\nDiagonal matrix from v:")
print(np.diag(v, 0))

Diagonal of A:
[1 5 9]

Diagonal matrix from v:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
# Random array with seed
from numpy.random import default_rng
rng = default_rng(42)
rng.random((3, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [14]:
# linspace(1,3,4) → np.linspace(1,3,4)
np.linspace(1, 3, 4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [15]:
# meshgrid for 2D grids
X, Y = np.meshgrid(np.arange(0, 3), np.arange(0, 3))
print("X grid:")
print(X)
print("\nY grid:")
print(Y)

X grid:
[[0 1 2]
 [0 1 2]
 [0 1 2]]

Y grid:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [16]:
# zeros(3,4,5) → np.zeros((3,4,5)) - 3D array
print("3D zeros array shape:", np.zeros((3, 4, 5)).shape)

3D zeros array shape: (3, 4, 5)


## Section 3: Indexing and Slicing

In [17]:
# a(end) → a[-1]: Last element
print("Last element of v:", v[-1])

Last element of v: 3


In [18]:
# a(2,5) → a[1, 4]: Element access (2nd row, 5th column)
large_mat = np.arange(30).reshape(5, 6)
print("Element at [1, 4]:", large_mat[1, 4])

Element at [1, 4]: 10


In [19]:
# a(2,:) → a[1] or a[1, :]: Entire second row
print("Second row of a:", a[1])

Second row of a: [4 5 6]


In [20]:
# a(1:3,:) → a[0:3]: First 3 rows
print("First 3 rows of A:")
print(A[0:3])

First 3 rows of A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# a(end-4:end,:) → a[-5:]: Last 5 rows
M = np.arange(1, 26).reshape(5, 5)
print("Last 5 rows (all rows in this 5x5 matrix):")
print(M[-5:])

Last 5 rows (all rows in this 5x5 matrix):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
# a(1:3,5:9) → a[0:3,4:9]: Submatrix selection
large_matrix = np.arange(1, 46).reshape(5, 9)
print("Rows 1-3, columns 5-9:")
print(large_matrix[0:3, 4:9])

Rows 1-3, columns 5-9:
[[ 5  6  7  8  9]
 [14 15 16 17 18]
 [23 24 25 26 27]]


In [23]:
# a([2,4,5],[1,3]) → a[np.ix_([1,3,4],[0,2])]: Advanced indexing
M9 = np.arange(1, 82).reshape(9, 9)
print("Select rows 2,4,5 and columns 1,3:")
print(M9[np.ix_([1, 3, 4], [0, 2])])

Select rows 2,4,5 and columns 1,3:
[[10 12]
 [28 30]
 [37 39]]


In [24]:
# a(3:2:21,:) → a[2:21:2,:]: Step slicing
Big = np.arange(1, 67).reshape(22, 3)
print("Every other row from 3rd to 21st:")
print(Big[2:21:2, :])

Every other row from 3rd to 21st:
[[ 7  8  9]
 [13 14 15]
 [19 20 21]
 [25 26 27]
 [31 32 33]
 [37 38 39]
 [43 44 45]
 [49 50 51]
 [55 56 57]
 [61 62 63]]


In [25]:
# a(1:2:end,:) → a[::2,:]: Every other row
print("Every other row of M:")
print(M[::2, :])

Every other row of M:
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [26]:
# a(end:-1:1,:) → a[::-1,:]: Reverse rows
print("A with reversed rows:")
print(A[::-1,:])

A with reversed rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [27]:
# a([1:end 1],:) → a[np.r_[:len(a),0],:]: Append first row to end
print("Append first row to end:")
print(a[np.r_[:len(a), 0], :])

Append first row to end:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


## Section 4: Array Manipulation

In [28]:
# Transpose operations
print("a.T (transpose):")
print(a.T)

# Complex conjugate transpose
C = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
print("\nC.conj().T (conjugate transpose):")
print(C.conj().T)

a.T (transpose):
[[1 4]
 [2 5]
 [3 6]]

C.conj().T (conjugate transpose):
[[1.-2.j 5.-6.j]
 [3.-4.j 7.-8.j]]


In [29]:
# repmat(a, m, n) → np.tile(a, (m, n))
small = np.array([[1, 2], [3, 4]])
print("Original 2x2:")
print(small)
print("\nTiled 2x3:")
print(np.tile(small, (2, 3)))

Original 2x2:
[[1 2]
 [3 4]]

Tiled 2x3:
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [30]:
# Array concatenation
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Horizontal concatenate [a b] → np.hstack:")
print(np.hstack((arr1, arr2)))
print("\nVertical concatenate [a; b] → np.vstack:")
print(np.vstack((arr1, arr2)))

Horizontal concatenate [a b] → np.hstack:
[[1 2 5 6]
 [3 4 7 8]]

Vertical concatenate [a; b] → np.vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
# Block matrix construction
a_block = np.array([[1, 2], [3, 4]])
b_block = np.array([[5, 6], [7, 8]])
c_block = np.array([[9, 10], [11, 12]])
d_block = np.array([[13, 14], [15, 16]])
block_matrix = np.block([[a_block, b_block], [c_block, d_block]])
print("Block matrix from 2x2 blocks:")
print(block_matrix)

Block matrix from 2x2 blocks:
[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]


In [32]:
# flatten() - Turn array into vector
print("A.flatten():", A.flatten())
print("A.flatten('F') - MATLAB column-major order:", A.flatten('F'))

A.flatten(): [1 2 3 4 5 6 7 8 9]
A.flatten('F') - MATLAB column-major order: [1 4 7 2 5 8 3 6 9]


In [33]:
# squeeze() - Remove singleton dimensions
arr_with_singleton = np.array([[[1], [2], [3]]])
print("Shape before squeeze:", arr_with_singleton.shape)
print("Shape after squeeze:", arr_with_singleton.squeeze().shape)

Shape before squeeze: (1, 3, 1)
Shape after squeeze: (3,)


## Section 5: Arithmetic Operations

In [34]:
# Matrix multiplication (a * b → a @ b)
print("A @ B (matrix multiplication):")
print(A @ B)

A @ B (matrix multiplication):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [35]:
# Element-wise multiplication (a .* b → a * b)
print("A * B (element-wise multiplication):")
print(A * B)

A * B (element-wise multiplication):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [36]:
# Element-wise division (a./b → a/b)
print("A / B (element-wise division):")
print(A / B)

A / B (element-wise division):
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [37]:
# Element-wise power (a.^3 → a**3)
print("a**3 (element-wise power):")
print(a**3)

a**3 (element-wise power):
[[  1   8  27]
 [ 64 125 216]]


In [38]:
# Matrix power
print("Matrix power A^2:")
print(np.linalg.matrix_power(A, 2))

Matrix power A^2:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Section 6: Comparison and Logical Operations

In [39]:
# Comparison (a > 0.5)
test_arr = np.array([[0.1, 0.6], [0.3, 0.8]])
print("Array:")
print(test_arr)
print("\nElements > 0.5:")
print(test_arr > 0.5)

Array:
[[0.1 0.6]
 [0.3 0.8]]

Elements > 0.5:
[[False  True]
 [False  True]]


In [40]:
# find(a > 0.5) → np.nonzero(a > 0.5)
print("Indices where elements > 0.5:")
print(np.nonzero(test_arr > 0.5))

Indices where elements > 0.5:
(array([0, 1]), array([1, 1]))


In [41]:
# Column selection with boolean condition
Acols = np.arange(1, 13).reshape(3, 4).astype(float)
vv = np.array([0.2, 0.7, 0.6, 0.1])
print("Matrix:")
print(Acols)
print("\nVector for column selection:", vv)
print("\nSelect columns where v>0.5:")
print(Acols[:, np.nonzero(vv > 0.5)[0]])

Matrix:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Vector for column selection: [0.2 0.7 0.6 0.1]

Select columns where v>0.5:
[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]]


In [42]:
# Set elements < 0.5 to zero
test_copy = test_arr.copy()
test_copy[test_copy < 0.5] = 0
print("Set elements < 0.5 to zero:")
print(test_copy)

Set elements < 0.5 to zero:
[[0.  0.6]
 [0.  0.8]]


In [43]:
# a .* (a>0.5) → a * (a>0.5): Mask multiplication
mm = np.array([[0.1, 0.7], [0.3, 0.8]])
print("Original:")
print(mm)
print("\nMasked (elements <0.5 become 0):")
print(mm * (mm > 0.5))

Original:
[[0.1 0.7]
 [0.3 0.8]]

Masked (elements <0.5 become 0):
[[0.  0.7]
 [0.  0.8]]


In [44]:
# a(:)=3 → a[:]=3: Full assignment
tmp = np.array([[1, 2], [3, 4]])
tmp[:] = 3
print("Array after a[:]=3:")
print(tmp)

Array after a[:]=3:
[[3 3]
 [3 3]]


In [45]:
# Logical operations
bool_a = np.array([True, False, True])
bool_b = np.array([True, True, False])
print("a:", bool_a)
print("b:", bool_b)
print("logical_and(a, b):", np.logical_and(bool_a, bool_b))
print("logical_or(a, b):", np.logical_or(bool_a, bool_b))

a: [ True False  True]
b: [ True  True False]
logical_and(a, b): [ True False False]
logical_or(a, b): [ True  True  True]


In [46]:
# Bitwise operations
int_a = np.array([1, 2, 3])
int_b = np.array([3, 2, 1])
print("a:", int_a)
print("b:", int_b)
print("a & b (bitwise AND):", int_a & int_b)
print("a | b (bitwise OR):", int_a | int_b)

a: [1 2 3]
b: [3 2 1]
a & b (bitwise AND): [1 2 1]
a | b (bitwise OR): [3 2 3]


## Section 7: Mathematical Functions

In [47]:
# max() operations
print("A.max() - Maximum element:", A.max())
print("A.max(0) - Max of each column:", A.max(0))
print("A.max(1) - Max of each row:", A.max(1))
print("\nnp.maximum(A, B) - Element-wise max:")
print(np.maximum(A, B))

A.max() - Maximum element: 9
A.max(0) - Max of each column: [7 8 9]
A.max(1) - Max of each row: [3 6 9]

np.maximum(A, B) - Element-wise max:
[[9 8 7]
 [6 5 6]
 [7 8 9]]


In [48]:
# Vector norm
print("np.linalg.norm(v) - L2 norm of v:", np.linalg.norm(v))
print("Alternative np.sqrt(v @ v):", np.sqrt(v @ v))

np.linalg.norm(v) - L2 norm of v: 3.7416573867739413
Alternative np.sqrt(v @ v): 3.7416573867739413


In [49]:
# unique(a) → np.unique(a)
arr_with_dups = np.array([1, 2, 2, 3, 3, 3, 4])
print("Array with duplicates:", arr_with_dups)
print("Unique values:", np.unique(arr_with_dups))

Array with duplicates: [1 2 2 3 3 3 4]
Unique values: [1 2 3 4]


In [50]:
# Dot product
print("np.dot(x, y):", np.dot(x, y))

np.dot(x, y): 32


In [51]:
# Outer product
print("np.outer(x, y):")
print(np.outer(x, y))

np.outer(x, y):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [52]:
# Cross product
print("np.cross(x, y):", np.cross(x, y))

np.cross(x, y): [-3  6 -3]


## Section 8: Linear Algebra

In [53]:
# Matrix determinant
print("np.linalg.det(A):", np.linalg.det(A))

np.linalg.det(A): 0.0


In [54]:
# Matrix trace
print("np.trace(A) - Sum of diagonal elements:", np.trace(A))

np.trace(A) - Sum of diagonal elements: 15


In [55]:
# Matrix norms
print("Frobenius norm:", np.linalg.norm(A, 'fro'))
print("2-norm:", np.linalg.norm(A, 2))
print("1-norm:", np.linalg.norm(A, 1))
print("Infinity norm:", np.linalg.norm(A, np.inf))

Frobenius norm: 16.881943016134134
2-norm: 16.84810335261421
1-norm: 18.0
Infinity norm: 24.0


In [56]:
# Matrix inverse - inv(a) → linalg.inv(a)
A_inv = np.array([[1, 2], [3, 4]])
print("Matrix:")
print(A_inv)
print("\nInverse:")
print(np.linalg.inv(A_inv))

Matrix:
[[1 2]
 [3 4]]

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
# Pseudo-inverse - pinv(a) → linalg.pinv(a)
print("Pseudo-inverse of A:")
print(np.linalg.pinv(A))

Pseudo-inverse of A:
[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  4.20756436e-17  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


In [58]:
# Matrix rank - rank(a) → np.linalg.matrix_rank(a)
print("Rank of A:", np.linalg.matrix_rank(A))

Rank of A: 2


In [59]:
# Solve linear system a\b → linalg.solve(a, b)
A_sys = np.array([[3, 1], [1, 2]])
b_sys = np.array([9, 8])
print("System: Ax = b")
print("A:")
print(A_sys)
print("b:", b_sys)
print("\nSolution x:", np.linalg.solve(A_sys, b_sys))

System: Ax = b
A:
[[3 1]
 [1 2]]
b: [9 8]

Solution x: [2. 3.]


In [60]:
# Right division: b/a (solve x*a = b)
A2 = np.array([[3., 1.], [1., 2.]])
brow = np.array([[9., 8.]])
x_right = np.linalg.solve(A2.T, brow.T).T
print("Solve x*A = b (right division):")
print("x:", x_right)
print("Verification x @ A2:", x_right @ A2)

Solve x*A = b (right division):
x: [[2. 3.]]
Verification x @ A2: [[9. 8.]]


In [61]:
# Least squares - linalg.lstsq(a, b)
solution, residuals, rank, s = np.linalg.lstsq(A, v, rcond=None)
print("Least squares solution for Ax = v:", solution)

Least squares solution for Ax = v: [-0.05555556  0.11111111  0.27777778]


In [62]:
# Linear regression Z\y
Z = np.column_stack([np.ones(10), np.arange(10)])
y_reg = 2 + 3*np.arange(10) + np.random.randn(10)*0.1
x_reg, residuals, rank, s = np.linalg.lstsq(Z, y_reg, rcond=None)
print("Linear regression coefficients [intercept, slope]:", x_reg)

Linear regression coefficients [intercept, slope]: [2.12709355 2.98267299]


In [63]:
# SVD - [U,S,V]=svd(a) → U, S, Vh = linalg.svd(a)
U, S, Vh = np.linalg.svd(A)
print("U shape:", U.shape)
print("S (singular values):", S)
print("Vh shape:", Vh.shape)

U shape: (3, 3)
S (singular values): [1.68481034e+01 1.06836951e+00 4.41842475e-16]
Vh shape: (3, 3)


In [64]:
# Cholesky - chol(a) → linalg.cholesky(a)
A_pd = np.array([[4, 2], [2, 3]])
print("Positive definite matrix:")
print(A_pd)
print("\nCholesky factor:")
print(np.linalg.cholesky(A_pd))

Positive definite matrix:
[[4 2]
 [2 3]]

Cholesky factor:
[[2.         0.        ]
 [1.         1.41421356]]


In [65]:
# Eigenvalues - [V,D]=eig(a) → D,V = linalg.eig(a)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [66]:
# Generalized eigenvalue problem [V,D]=eig(a,b)
Agen = np.array([[5., 2.], [2., 3.]])
Bgen = np.array([[4., 1.], [1., 2.]])
Dg, Vg = scipy.linalg.eig(Agen, Bgen)
print("Generalized eigenvalues:", Dg)

Generalized eigenvalues: [1.        +0.j 1.57142857+0.j]


In [67]:
# Sparse eigenvalues - [V,D]=eigs(a,3)
S = np.array([[2., 1., 0.],
              [1., 2., 1.],
              [0., 1., 2.]])

# For symmetric matrices, use eigsh
ws, vs = eigsh((S + S.T)/2, k=2, which='LA')
print("2 largest eigenvalues (symmetric case):", ws)

2 largest eigenvalues (symmetric case): [2.         3.41421356]


In [68]:
# QR decomposition - [Q,R]=qr(a) → Q,R = linalg.qr(a)
Q, R = np.linalg.qr(A)
print("Q:")
print(Q)
print("\nR:")
print(R)

Q:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

R:
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [69]:
# LU decomposition - [L,U,P]=lu(a) → P,L,U = linalg.lu(a)
P_lu, L_lu, U_lu = scipy.linalg.lu(A)
print("P:")
print(P_lu)
print("\nL:")
print(L_lu)
print("\nU:")
print(U_lu)
print("\nVerification - A ≈ P@L@U:")
print("Reconstruction error:", np.linalg.norm(A - P_lu @ L_lu @ U_lu))
print("Note: MATLAB's P = transpose(NumPy's P)")

P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U:
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

Verification - A ≈ P@L@U:
Reconstruction error: 0.0
Note: MATLAB's P = transpose(NumPy's P)


In [70]:
# Conjugate gradient solver - conjgrad → scipy.sparse.linalg.cg
SPD = np.array([[4., 1.], [1., 3.]])
bb = np.array([1., 2.])
x_cg, info = cg(SPD, bb)
print("CG solution:", x_cg)
print("Convergence info (0=success):", info)

CG solution: [0.09090909 0.63636364]
Convergence info (0=success): 0


## Section 9: Signal Processing

In [71]:
# FFT - fft(a) → np.fft.fft(a)
signal = np.array([1, 2, 3, 4])
print("Signal:", signal)
print("FFT:", np.fft.fft(signal))

Signal: [1 2 3 4]
FFT: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [72]:
# Inverse FFT - ifft(a) → np.fft.ifft(a)
fft_result = np.fft.fft(signal)
print("IFFT of FFT (should recover original signal):", np.fft.ifft(fft_result).real)

IFFT of FFT (should recover original signal): [1. 2. 3. 4.]


In [73]:
# decimate(x,q) → scipy.signal.decimate(x,q): Downsample with filtering
sig = np.linspace(0, 10, 100)
decim = decimate(sig, 4, zero_phase=True)
print("Original length → Decimated length:", len(sig), "→", len(decim))

Original length → Decimated length: 100 → 25


In [74]:
# Resampling alternative
resampled = scipy.signal.resample(sig, int(np.ceil(len(sig)/4)))
print("Resampled length:", len(resampled))

Resampled length: 25


## Section 10: Sorting

In [75]:
# sort(a) → np.sort(a)
unsorted = np.array([[3, 1, 2], [6, 4, 5]])
print("Original array:")
print(unsorted)
print("\nSort each column (axis=0):")
print(np.sort(unsorted, axis=0))
print("\nSort each row (axis=1):")
print(np.sort(unsorted, axis=1))

Original array:
[[3 1 2]
 [6 4 5]]

Sort each column (axis=0):
[[3 1 2]
 [6 4 5]]

Sort each row (axis=1):
[[1 2 3]
 [4 5 6]]


In [76]:
# Sort rows by first column
to_sort = np.array([[3, 1], [1, 2], [2, 3]])
print("Original:")
print(to_sort)
I = np.argsort(to_sort[:, 0])
sorted_arr = to_sort[I, :]
print("\nSorted by first column:")
print(sorted_arr)

Original:
[[3 1]
 [1 2]
 [2 3]]

Sorted by first column:
[[1 2]
 [2 3]
 [3 1]]


## Section 11: Additional Operations

In [77]:
# Creating ranges
print("1:10 → np.arange(1., 11.):", np.arange(1., 11.))
print("0:9 → np.arange(10.):", np.arange(10.))
print("Alternative np.r_[1:11]:", np.r_[1:11])

1:10 → np.arange(1., 11.): [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
0:9 → np.arange(10.): [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Alternative np.r_[1:11]: [ 1  2  3  4  5  6  7  8  9 10]


In [78]:
# Creating column vector
col_vec = np.arange(1., 6.)[:, np.newaxis]
print("Column vector shape:", col_vec.shape)
print("Column vector:")
print(col_vec)

Column vector shape: (5, 1)
Column vector:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [79]:
# Copy operations - y=x(2,:) → y=x[1,:].copy()
xx = np.arange(1, 7).reshape(2, 3)
yy = xx[1, :].copy()
yy[0] = 999
print("Original x (unchanged):", xx[1, :])
print("Modified copy y:", yy)
print("\nImportant: NumPy slices are views by default, use .copy() for independent copy")

Original x (unchanged): [4 5 6]
Modified copy y: [999   5   6]

Important: NumPy slices are views by default, use .copy() for independent copy


In [80]:
# Grid generation methods
gx, gy = np.mgrid[0:3, 0:4]
print("mgrid (dense) shapes:", gx.shape, gy.shape)

ogx, ogy = np.ogrid[0:3, 0:4]
print("ogrid (sparse) shapes:", ogx.shape, ogy.shape)

ixX, ixY = np.ix_(np.arange(3), np.arange(4))
print("ix_ (for broadcasting) shapes:", ixX.shape, ixY.shape)

mgrid (dense) shapes: (3, 4) (3, 4)
ogrid (sparse) shapes: (3, 1) (1, 4)
ix_ (for broadcasting) shapes: (3, 1) (1, 4)
